include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    prefer_constructors_over_static_methods: false
    avoid_positional_boolean_parameters: false
    # TODO: re-enable this when going to production
    avoid_print: false
